name: Release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build-macos:
    runs-on:
      - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set Variables
        id: set_variables
        run: |
          echo "version=$(cat cloudlift/version/__init__.py | cut -d'=' -f2 | tr -d "'" | tr -d ' ')" >> $GITHUB_ENV

          package_name=$(/bin/bash build.sh --package-name)
          echo "Package Name: $package_name"
          echo "package_name=$package_name" >> $GITHUB_ENV

      - name: Build
        run: /bin/bash build.sh

      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.package_name }}"
          path: "${{ github.workspace }}/dist/${{ env.package_name }}"

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Base Image (if not cached) # todo: move to separate job or use cache or upload to a docker registry
        run: |
          docker build \
            --tag centos7-py39 \
            --file bin/dockerfile-linux bin/

      - name: Create Container
        run: |
          docker run -d \
            --name cloudlift-build \
            -v ${{ github.workspace }}:/cloudlift \
            -w /cloudlift \
            centos7-py39 \
            tail -f /dev/null

      - name: Build Package
        run: |
          docker exec cloudlift-build /bin/bash build.sh

      - name: Set Variables
        id: set_variables
        run: |
          echo "version=$(cat cloudlift/version/__init__.py | cut -d'=' -f2 | tr -d "'" | tr -d ' ')" >> $GITHUB_ENV

          package_name=$(/bin/bash build.sh --package-name)
          echo "Package Name: $package_name"
          echo "package_name=$package_name" >> $GITHUB_ENV

      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.package_name }}"
          path: "${{ github.workspace }}/dist/${{ env.package_name }}"


  release:
    if: github.ref == 'refs/tags/v*.*.*'
    runs-on: ubuntu-latest
    needs:
      - build-macos
      - build-linux

    steps:
      - name: Get and Set Tag
        id: set_tag
        run: |
          tag=$(echo $GITHUB_REF | cut -d'/' -f3)
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "cloudlift-*.tar.gz"
          path: "${{ github.workspace }}"

      - name: Calculate SHA of Packages
        run: |
          shopt -s nullglob  # Allow expansion of patterns with no matches
          find "${{ github.workspace }}" -type f -name "cloudlift*.tar.gz" | while read -r file; do
            sha=$(shasum -a 256 "$file" | cut -d' ' -f1)
            file=$(basename "$file")
            echo "$file: $sha" >> checksums.txt
          done

      - name: Debug
        run: |
          tree "${{ github.workspace }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/tags/v${{ env.version }}'
        with:
          files: |
            **/*.tar.gz
            checksums.txt
          tag_name: ${{ env.tag }}
          name: "Release ${{ env.tag }}"
          body: |
            Changes in this Release
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
