name: Release

on:
  push:
    # branches:
    #   - dev
    #   - master
    tags:
      - "v*.*.*"

jobs:
  build-macos:
    runs-on:
      - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Set Variables
        id: set_variables
        run: |
          echo "version=$(cat cloudlift/version/__init__.py | cut -d'=' -f2 | tr -d "'" | tr -d ' ')" >> $GITHUB_ENV

          package_name=$(/bin/bash build.sh --package-name)
          echo "Package Name: $package_name"
          echo "package_name=$package_name" >> $GITHUB_ENV

      - name: Build
        run: /bin/bash build.sh

      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.package_name }}"
          path: "${{ github.workspace }}/dist/${{ env.package_name }}"

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Base Image (if not cached) # todo: move to separate job or use cache or upload to a docker registry
        run: |
          docker build \
            --tag centos7-py39 \
            --file bin/dockerfile-linux bin/

      - name: Create Container
        run: |
          docker run -d \
            --name cloudlift-build \
            -v ${{ github.workspace }}:/cloudlift \
            -w /cloudlift \
            centos7-py39 \
            tail -f /dev/null

      - name: Build Package
        run: |
          docker exec cloudlift-build /bin/bash build.sh

      - name: Set Variables
        id: set_variables
        run: |
          echo "version=$(cat cloudlift/version/__init__.py | cut -d'=' -f2 | tr -d "'" | tr -d ' ')" >> $GITHUB_ENV

          package_name=$(/bin/bash build.sh --package-name)
          echo "Package Name: $package_name"
          echo "package_name=$package_name" >> $GITHUB_ENV

      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.package_name }}"
          path: "${{ github.workspace }}/dist/${{ env.package_name }}"

  test-macos:
    runs-on:
      - macos-latest
    needs: build-macos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Package Name
        run: |
          package_name=$(/bin/bash build.sh --package-name)
          echo "Package Name: $package_name"
          echo "package_name=$package_name" >> $GITHUB_ENV

      - name: Clean Workspace
        run: |
          rm -rf ${{ github.workspace }}/*

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: "${{ env.package_name }}"
          path: "${{ github.workspace }}"

      - name: Debug
        run: |
          ls -lah "${{ github.workspace }}"

      - name: Unpack Artifact
        run: |
          mkdir -p cloudlift
          tar -xzf "${{ github.workspace }}/${{ env.package_name }}" -C cloudlift --strip-components=1

      - name: Run Tests
        run: |
          ./cloudlift/cloudlift --version

          if [[ $? -ne 0 ]]; then
            echo "Failed to run cloudlift on macOS"
            exit 1
          fi

  test-linux:
    runs-on: ubuntu-latest
    needs:
      - build-linux

    steps:
      - name: Set Images for Testing
        run: |
          images=(
            "ubuntu:20.04"
            "ubuntu:22.04"
            "ubuntu:23.10"
            "ubuntu:24.04"
            "debian:12" # bookworm
            "debian:11" # bullseye
            "debian:10" # buster
            "amazonlinux:2023"
            "amazonlinux:2"
            "amazonlinux:1"
            "fedora:41"
            "fedora:40"
            "fedora:39"
            "fedora:38"
            "redhat/ubi8"
          )
          echo "images=${images[@]}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Linux Package Name
        run: |
          package_name=$(/bin/bash build.sh --package-name)
          echo "Package Name: $package_name"
          echo "package_name=$package_name" >> $GITHUB_ENV

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: "${{ env.package_name }}"
          path: "${{ github.workspace }}"

      - name: Unpack Artifact
        run: |
          mkdir -p cloudlift
          tar -xzf "${{ github.workspace }}/${{ env.package_name }}" -C cloudlift --strip-components=1

      - name: Run Tests
        run: |
          IFS=' ' read -r -a image_array <<< "${{ env.images }}"

          for image in "${image_array[@]}"; do
            echo "Testing on $image"
            docker_op=$(docker run --rm -v ${{ github.workspace }}/cloudlift:/cloudlift -w /cloudlift "$image" /bin/bash -c "./cloudlift --version")
            echo "$image: $docker_op"

            # remove docker image
            docker rmi "$image"

            # check if docker_op contains the version
            # if [[ $docker_op != *"${{ env.version }}"* ]]; then
            #   echo "Failed to run cloudlift on $image"
            #   exit 1
            # fi
          done

  release:
    if: github.ref == 'refs/tags/v*.*.*'
    runs-on: ubuntu-latest
    needs:
      - test-linux
      - test-macos

    steps:
      - name: Get and Set Tag
        id: set_tag
        run: |
          tag=$(echo $GITHUB_REF | cut -d'/' -f3)
          echo "tag=$tag" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "cloudlift-*.tar.gz"
          path: "${{ github.workspace }}"

      - name: Calculate SHA of Packages
        run: |
          shopt -s nullglob  # Allow expansion of patterns with no matches
          find "${{ github.workspace }}" -type f -name "cloudlift*.tar.gz" | while read -r file; do
            sha=$(shasum -a 256 "$file" | cut -d' ' -f1)
            file=$(basename "$file")
            echo "$file: $sha" >> checksums.txt
          done

      - name: Debug
        run: |
          ls -lah "${{ github.workspace }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/tags/v${{ env.version }}'
        with:
          files: |
            **/*.tar.gz
            checksums.txt
          tag_name: ${{ env.tag }}
          name: "Release ${{ env.tag }}"
          body: |
            Changes in this Release
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
